import "./globals.css";
import React from "react";

export const metadata = {
  title: "Hackathon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/logoXR.png" />
      </head>

      <body>{children}</body>
    </html>
  );
}
